### ISSUE TITLE
NoSuchBeanDefinitionException when running integration tests in applications with cache-ehcache installed

### ISSUE THREAD

**Issue by rlovtangen** [grails-plugins/grails-cache-ehcache#27]
Integration tests fails to run in applications with cache-ehcache installed.

Steps to reproduce:
1. $ grails create-app testapp
2. $ cd testapp
3. $ grails create-integration-test Foo
4. Add dependency to build.gradle: `compile "org.grails.plugins:cache-ehcache:2.0.0.BUILD-SNAPSHOT"`
5. $ ./gradlew integrationTest

Results in:

```
testapp.FooSpec > test something FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException
    java.lang.IllegalStateException at FooSpec.groovy:-1
```

Running `./gradlew integrationTest --debug` reveals that the problem is `mbeanServer`:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'mbeanServer' is defined
```

Tested with Grails 3.1.10

**Comment by rlovtangen** [comment]
My current workaround is to remove cache-ehcache jar during integration test, as my tests are not dependent on cache-ehcache being present.

````
configure(integrationTest) {
    //Remove cache-ehcache plugin when running integration test due to https://github.com/grails-plugins/grails-cache-ehcache/issues/27. Remove when issue is fixed
    classpath = classpath.filter{ File file ->
        !file.name.startsWith( "cache-ehcache-" )
    }
}
````

**Comment by PiotrZakrzewski** [comment]
Issue is still present in 3.0. Below link to the repo reproducing the error
https://github.com/PiotrZakrzewski/EhCacheJmxBug

**Comment by jameskleeh** [comment]
No longer an issue in 3.0
