### ISSUE TITLE
Lock timeout time exceeded

### ISSUE THREAD

**Issue by robertoschwald** [grails-plugins/grails-cache-ehcache#29]
While generating lots of caches programmatically I receive this exception from the GrailsEhcacheManager on high load:

```
net.sf.ehcache.CacheException: Failed to get lock for <cache_identifier> cache creation
	at grails.plugin.cache.ehcache.GrailsEhcacheCacheManager.getOrCreateCache(GrailsEhcacheCacheManager.java:75)
```

Seems the 200ms hardcoded timeout could not be enough, if hundreds of caches are generated at the same time. Maybe add a config option to set the timeout?

**Comment by jameskleeh** [comment]
Done
