### ISSUE TITLE
Need to register shutdown method with Spring on GrailsEhCacheManagerFactoryBean

### ISSUE THREAD

**Issue by jukin-jerry** [grails-plugins/grails-cache-ehcache#30]
On the 1.x codeline, at application shutdown, we see this warning:

> The web application [] appears to have started a thread named [grails-cache-ehcache] but has failed to stop it. This is very likely to create a memory leak.

Changing the configuration of the bean in the plugin's doWithSpring resolves the issue, eg.

```
		ehcacheCacheManager(GrailsEhCacheManagerFactoryBean) {  bean ->
			cacheManagerName = ehcacheCacheManagerName
			configLocation = ehcacheConfigLocation
			rebuildable = reloadable
                        bean.destroyMethod = 'destroy'
		}
```

Will create a PR.

**Comment by jukin-jerry** [comment]
Created PR 31

**Comment by jameskleeh** [comment]
Things were changed around, however this is done
